export var ActionTypes = {
  RECEIVE_RAW_QUESTIONS: 'RECEIVE_RAW_QUESTIONS',

  HOST_CLICK_CHOICE: 'HOST_CLICK_CHOICE',
  HOST_SELECT_QUESTION: 'HOST_SELECT_QUESTION'
};

export var PayloadSources = {
  SERVER_ACTION: 'SERVER_ACTION',
  VIEW_ACTION: 'VIEW_ACTION'
};

