export var ActionTypes = {
  RECEIVE_QUESTIONS: 'RECEIVE_QUESTIONS',
  RECEIVE_CHOICES: 'RECEIVE_CHOICES'
};

export var PayloadSources = {
  SERVER_ACTION: 'SERVER_ACTION',
  VIEW_ACTION: 'VIEW_ACTION'
};

