export var ActionTypes = {
  RECEIVE_RAW_QUESTIONS: 'RECEIVE_RAW_QUESTIONS',
  RECEIVE_RAW_TEAM_INFO: 'RECEIVE_RAW_TEAM_INFO',
  RECEIVE_CURRENT_QUESTION: 'RECEIVE_CURRENT_QUESTION',
  RECEIVE_BUTTON_PRESS: 'RECEIVE_BUTTON_PRESS',
  RECEIVE_BUTTONS_CLEARED: 'RECEIVE_BUTTONS_CLEARED',
  RECEIVE_REVEALED_CHOICES: 'RECEIVE_REVEALED_CHOICES',
  RECEIVE_WRONG_ANSWER: 'RECEIVE_WRONG_ANSWER',

  HOST_CLICK_CHOICE: 'HOST_CLICK_CHOICE',
  HOST_SELECT_QUESTION: 'HOST_SELECT_QUESTION',
  HOST_CLICK_ERROR_BUTTON: 'HOST_CLICK_ERROR_BUTTON'

};

export var PayloadSources = {
  SERVER_ACTION: 'SERVER_ACTION',
  VIEW_ACTION: 'VIEW_ACTION'
};

